### PR TITLE
WIP: Add copyright info to LICENSE

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hi :-) Some info like this draft needs to be included. I recommend to make it a team decision who & what exactly is listed there. Please don't merge as is, but only after adding more commits (or comments here) to record such a decision.

### CODE REVIEW

**Comment by johanneswerner** [comment]
Oh, this is embarassing. Thank you for the heads-up. I will clarify that with the two others this morning.

**Comment by johanneswerner** [comment]
So, does this mean

- running the program without argument should create the following output

```bash
mPies  Copyright (C) 2018  Johannes Werner (Leibniz-Institute for Baltic Sea Research), Augustin Geron, Sabine Matallana Surget (University of Stirling)

This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'. 
This is free software, and you are welcome to redistribute it
under certain conditions; type `show c' for details.
```

by the way, what does _show w_ and _show c_ mean?

- and in each file that contains programming code should start with 

```
# mPies (metaProteomics in environmental sciences) creates annotated databases for metaproteomic analysis.
# Copyright (C) 2018  Johannes Werner (Leibniz-Institute for Baltic Sea Research)
# Augustin Geron (University of Stirling)
# Sabine Matallana Surget (University of Stirling)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

(...)
```

**Comment by katrinleinweber** [comment]
No worries! It's a complex problem, and the templating is far from perfect. GitLab can auto-insert (at least some) of that info into (at least some of) the templates: https://docs.gitlab.com/ee/user/project/repository/web_editor.html#template-dropdowns

**Comment by johanneswerner** [comment]
In retrospect, it might have been wiser to do that when the repository was still managed in Gitlab. 

By the way, when #1 is done, would that be the time to attach a tag? And if so, rather 0.9 or 1.0?

**Comment by johanneswerner** [comment]
all authors approved

**Pull request merged**
